//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshopper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBrand
    {
        public tblBrand()
        {
            this.tblProducts = new HashSet<tblProduct>();
        }
    
        public int PK_iBrandID { get; set; }
        public string sBrandName { get; set; }
    
        public virtual ICollection<tblProduct> tblProducts { get; set; }
    }
}
