//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshopper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategory
    {
        public tblCategory()
        {
            this.tblCategory1 = new HashSet<tblCategory>();
            this.tblProducts = new HashSet<tblProduct>();
        }
    
        public int PK_iCategoryID { get; set; }
        public string sCategoryName { get; set; }
        public bool bParent { get; set; }
        public Nullable<int> SK_iCategoryID { get; set; }
    
        public virtual ICollection<tblCategory> tblCategory1 { get; set; }
        public virtual tblCategory tblCategory2 { get; set; }
        public virtual ICollection<tblProduct> tblProducts { get; set; }
    }
}
