//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshopper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public tblProduct()
        {
            this.tblReviews = new HashSet<tblReview>();
        }
    
        public int PK_iProductID { get; set; }
        public string sProductName { get; set; }
        public string sAvailability { get; set; }
        public int FK_iConditionID { get; set; }
        public double fCost { get; set; }
        public int FK_iCategoryID { get; set; }
        public int FK_iBrandID { get; set; }
        public string sDetail { get; set; }
        public string sImage01 { get; set; }
        public string sImage02 { get; set; }
        public string sImage03 { get; set; }
        public string sImage04 { get; set; }
    
        public virtual tblBrand tblBrand { get; set; }
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblCondition tblCondition { get; set; }
        public virtual ICollection<tblReview> tblReviews { get; set; }
    }
}
